---
# Source: meshery/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshery-server
  namespace: meshery
  labels:
    helm.sh/chart: meshery-0.7.0
    app.kubernetes.io/name: meshery
    app.kubernetes.io/instance: meshery-core
    app.kubernetes.io/managed-by: Helm
---
# Source: meshery/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshery-server
  labels:
    helm.sh/chart: meshery-0.7.0
    app.kubernetes.io/name: meshery
    app.kubernetes.io/instance: meshery-core
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs: ["/metrics", "/health", "/ping"]
  verbs:
  - get
---
# Source: meshery/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshery-server
  labels:
    helm.sh/chart: meshery-0.7.0
    app.kubernetes.io/name: meshery
    app.kubernetes.io/instance: meshery-core
    app.kubernetes.io/managed-by: Helm
roleRef:
  kind: ClusterRole
  name: meshery-server
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: meshery-server
  namespace: meshery
---
# Source: meshery/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: meshery
  namespace: meshery
  labels:
    helm.sh/chart: meshery-0.7.0
    app.kubernetes.io/name: meshery
    app.kubernetes.io/instance: meshery-core
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  type: LoadBalancer
  ports:
    - port: 9081
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: meshery
    app.kubernetes.io/instance: meshery-core
---
# Source: meshery/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshery
  namespace: meshery
  labels:
    helm.sh/chart: meshery-0.7.0
    app.kubernetes.io/name: meshery
    app.kubernetes.io/instance: meshery-core
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: meshery
      app.kubernetes.io/instance: meshery-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meshery
        app.kubernetes.io/instance: meshery-core
    spec:
      restartPolicy: Always
      serviceAccountName: meshery-server
      securityContext:
        {}
      containers:
        - name: meshery
          securityContext:
            {}
          image: "n2h9/meshery:2025-03-16.01"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: ADAPTER_URLS
            value: meshery-istio:10000 meshery-linkerd:10001 meshery-consul:10002 meshery-kuma:10007 meshery-nginx-sm:10010 meshery-nsm:10004 meshery-app-mesh:10005 meshery-traefik-mesh:10006 meshery-cilium:10012
          - name: EVENT
            value: mesheryLocal
          - name: KEYS_PATH
            value: ../../server/permissions/keys.csv
          - name: MESHERY_SERVER_CALLBACK_URL
            value: 
          - name: PROVIDER
            value: 
          - name: PROVIDER_BASE_URLS
            value: https://cloud.layer5.io
          resources:
            {}
