---
# Source: meshery-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshery-operator
  namespace: meshery
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
---
# Source: meshery-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshery-metrics-reader
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
# Source: meshery-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshery-operator-role
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - meshery.io
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meshery.io
  resources:
  - brokers/status
  verbs:
  - get
  - patch
  - update
---
# Source: meshery-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshery-proxy-role
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
# Source: meshery-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshery-controller-role
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# Source: meshery-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshery-operator-rolebinding
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meshery-operator-role
subjects:
- kind: ServiceAccount
  name: meshery-operator
  namespace: meshery
---
# Source: meshery-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshery-proxy-rolebinding
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meshery-proxy-role
subjects:
- kind: ServiceAccount
  name: meshery-operator
  namespace: meshery
---
# Source: meshery-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshery-controller-rolebinding
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meshery-controller-role
subjects:
  - kind: ServiceAccount
    name: meshery-operator
    namespace: meshery
---
# Source: meshery-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meshery-leader-election-role
  namespace: meshery
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
# Source: meshery-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meshery-leader-election-rolebinding
  namespace: meshery
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: meshery-leader-election-role
subjects:
- kind: ServiceAccount
  name: meshery-operator
  namespace: meshery
---
# Source: meshery-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: meshery-operator
  namespace: meshery
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - port: 10000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
---
# Source: meshery-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshery-operator
  namespace: meshery
  labels:
    helm.sh/chart: meshery-operator-0.8.0
    app.kubernetes.io/name: meshery-operator
    app.kubernetes.io/instance: meshery-operator
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: meshery-operator
      app.kubernetes.io/instance: meshery-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meshery-operator
        app.kubernetes.io/instance: meshery-operator
    spec:
      serviceAccountName: meshery-operator
      securityContext:
        {}
      containers:
        - name: manager
          securityContext:
            {}
          # TODO: Need to confirm the meshery-operator image version
          image: "layer5/meshery-operator:stable-latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 9443
              # hostPort: 9443
              name: server
            - containerPort: 8080
              # TODO it's not a good idea we take account to the 8080 port, is there we need communicate through the physical ports
              # hostPort: 8080
              name: metrics
          env:
          args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          resources:
            {}
          command:
            - /manager
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
          imagePullPolicy: Always
          ports:
          - name: https
            containerPort: 8443
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=false
            - --v=10
          resources:
            {}
---
# Source: meshery-operator/charts/meshery-broker/templates/meshery_v1alpha1_broker_cr.tpl
apiVersion: meshery.io/v1alpha1
kind: Broker
metadata:
  name: meshery-broker
  namespace: meshery
spec:
  size: 1
---
# Source: meshery-operator/charts/meshery-meshsync/templates/meshery_v1alpha1_broker_cr.tpl
apiVersion: meshery.io/v1alpha1
kind: MeshSync
metadata:
  name: meshery-meshsync
  namespace: meshery
spec:
  size: 1
  broker:
    native:
      name: meshery-broker
      namespace: meshery
  watch-list:
    data:
      whitelist: "[{\"Resource\":\"grafanas.v1beta1.grafana.integreatly.org\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"prometheuses.v1.monitoring.coreos.com\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"namespaces.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"configmaps.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"nodes.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"secrets.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"persistentvolumes.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"persistentvolumeclaims.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"replicasets.v1.apps\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"pods.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"services.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"deployments.v1.apps\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"statefulsets.v1.apps\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"daemonsets.v1.apps\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"ingresses.v1.networking.k8s.io\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"endpoints.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"endpointslices.v1.discovery.k8s.io\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"cronjobs.v1.batch\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"replicationcontrollers.v1.\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"storageclasses.v1.storage.k8s.io\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"clusterroles.v1.rbac.authorization.k8s.io\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"volumeattachments.v1.storage.k8s.io\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]},{\"Resource\":\"apiservices.v1.apiregistration.k8s.io\",\"Events\":[\"ADDED\",\"MODIFIED\",\"DELETED\"]}]"
